# Site wide configuration

title: "[ Zombies Reimagined ]"
description: A Critical Discourse Analysis of Popular Culture
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: http://ds.swarthmore.edu/zombies-reimagined
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Swarthmore College Library Digital Scholarship
  email: digitalscholarship@swarthmore.edu
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: logo-mccabe-web.png # 160x160 px image for author byline
  disqus-shortname:

# prose.io front matter settings

# title: "Challenging Normal: A Linguistic Exploration of Horror & Sci-Fi"
# layout: article
# author: group4
# modified: 2016-04-27
# image:
#     feature:
#     teaser: White-Zombie-poster-3.jpg
#     thumb:
# storymap:
#     id:
#     title:
# timeline:
#     id: 1uGjhA8mK551YwHW1wRF5sh1utOxDV73JfuJbILe2jOI

prose:
  rooturl: '_posts/articles'
  media: 'images'
  metadata:
    _posts/articles:
      - name: 'title'
        field:
            element: "text"
            label: "Title"
            placeholder: "Title of the post"
            help: "The title does not need to be included in the text below"
            value: "article"
      - name: 'layout'
        field:
            element: "hidden"
            value: "article"
      - name: 'author'
        field:
            element: "hidden"
            value: "group5"
      - name: 'group_members'
        field:
            element: "text"
            label: "Group members"
      - name: 'modified'
        field:
            element: "hidden"
            value: CURRENT_DATETIME

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - vendor
